// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "OpenSVC SAS",
            "url": "https://www.opensvc.com",
            "email": "collector-api-contact@opensvc.com"
        },
        "license": {
            "name": "Apache License 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/node/token": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an authentication token from a node's credentials submitted with basic login.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get a node authentication token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.TokenResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/user/token": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an authentication token from a user's credentials submitted with basic login.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get a user authentication token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.TokenResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List nodes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "List nodes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The app code of the nodes is forced to one the user is responsible of.\nThe team responsible of the nodes defaults to the user's primary group.\nThe user must be in the NodeManager privilege group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Create or update nodes",
                "parameters": [
                    {
                        "description": "list of nodes to create or update",
                        "name": "nodes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Node"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Node"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes/tags": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List tags attachments to nodes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes/tags/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags",
                    "nodes"
                ],
                "summary": "Show a tag attachment to a node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.NodeTag"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Show a node by index, id or name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Show a node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Node"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The user must be in the NodeManager privilege group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Update a node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "node properties to create or update",
                        "name": "nodes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tables.Node"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Node"
                            }
                        }
                    },
                    "401": {
                        "description": "missing NodeManager privilege",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "the entry to update does not exist",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a node by index, id or name.\nThe user must have the NodeManager privilege.\nThe user must be responsible for the node, via app responsibles.\nCascade delete on services instances, dashboard entries, checks, packages and patches.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Delete a node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Node"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes/{id}/candidate_tags": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List existing tags not already attached to a node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes/{id}/tags": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List tags attached to a node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes/{id}/tags/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags",
                    "nodes"
                ],
                "summary": "Show a tag attachment to a node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.NodeTag"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "List services",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services/tags": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List tags attachments to services",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services/tags/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags",
                    "services"
                ],
                "summary": "Show a tag attachment to a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.ServiceTag"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Show a service by index, id or name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Show a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Service"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services/{id}/candidate_tags": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List existing tags not already attached to a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services/{id}/tags": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List tags attached to a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/services/{id}/tags/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags",
                    "services"
                ],
                "summary": "Show a tag attachment to a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.ServiceTag"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creating tags requires no privilege.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Create or update tags",
                "parameters": [
                    {
                        "description": "list of tags to create or update",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Tag"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Tag"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deleting tags requires the TagManager privilege.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Delete tags",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Tag"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tags/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Show a tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Tag"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a tag by index, uuid or name.\nRequires the TagManager privilege.\nCascade deletes the tag attachements to nodes and services.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Delete a tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.Tag"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tags/{id}/nodes": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List nodes having a specific tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tags/{id}/services": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List services having a specific tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The user must be in the UserManager privilege group to modify tiers users properties.\nThe user must be in the SelfManager privilege group to modify its user properties.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create or update users",
                "parameters": [
                    {
                        "description": "list of users to create or update",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.User"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Show a user by index, email or login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Show a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or uuid, or name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a user by index, email or login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the index of the entry in database, or email, or login name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tables.User"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}/apps/publication": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Managers and UserManager are allowed to see all users' information.\nOthers can only see information for users in their organization groups.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List apps the user can read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}/apps/responsible": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Managers and UserManager are allowed to see all users' information.\nOthers can only see information for users in their organization groups.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List apps the user is a responsible of",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}/groups": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Managers and UserManager are allowed to see all users' information.\nOthers can only see information for users in their organization groups.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List groups the user is a member of",
                "parameters": [
                    {
                        "type": "string",
                        "description": "properties to include, and optionally remap (comma separated)",
                        "name": "props",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to group by (comma separated)",
                        "name": "groupby",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "properties to order by (comma separated, prefix with '~' to reverse)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "property value filter (a, !a, a\u0026b, a|b, (a,b),  a%,  a%\u0026!ab%)",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of objets to include in response",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset of the first objet to include in response",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "turn off metadata in response",
                        "name": "meta",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.TableResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "meta": {
                    "$ref": "#/definitions/db.tableResponseMeta"
                }
            }
        },
        "db.property": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "remap": {
                    "type": "string"
                },
                "table": {
                    "type": "string"
                }
            }
        },
        "db.tableResponseMeta": {
            "type": "object",
            "properties": {
                "available_props": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.property"
                    }
                },
                "count": {
                    "type": "integer"
                },
                "included_props": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.property"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "routes.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "token_expire_at": {
                    "type": "string"
                }
            }
        },
        "tables.Node": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "app": {
                    "type": "string"
                },
                "asset_env": {
                    "type": "string"
                },
                "assetname": {
                    "type": "string"
                },
                "bios_version": {
                    "type": "string"
                },
                "cluster_id": {
                    "type": "string"
                },
                "collector": {
                    "type": "string"
                },
                "connect_to": {
                    "type": "string"
                },
                "cpu_cores": {
                    "type": "integer"
                },
                "cpu_dies": {
                    "type": "integer"
                },
                "cpu_freq": {
                    "type": "integer"
                },
                "cpu_model": {
                    "type": "string"
                },
                "cpu_threads": {
                    "type": "integer"
                },
                "cpu_vendor": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "enclosure": {
                    "type": "string"
                },
                "enclosureslot": {
                    "type": "string"
                },
                "fqdn": {
                    "type": "string"
                },
                "hv": {
                    "type": "string"
                },
                "hvpool": {
                    "type": "string"
                },
                "hvvdc": {
                    "type": "string"
                },
                "hw_obs_alert_date": {
                    "type": "string"
                },
                "hw_obs_warn_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_boot": {
                    "type": "string"
                },
                "last_comm": {
                    "type": "string"
                },
                "listener_port": {
                    "type": "integer"
                },
                "loc_addr": {
                    "type": "string"
                },
                "loc_building": {
                    "type": "string"
                },
                "loc_city": {
                    "type": "string"
                },
                "loc_country": {
                    "type": "string"
                },
                "loc_floor": {
                    "type": "string"
                },
                "loc_rack": {
                    "type": "string"
                },
                "loc_room": {
                    "type": "string"
                },
                "loc_zip": {
                    "type": "string"
                },
                "maintenance_end": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "mem_banks": {
                    "type": "integer"
                },
                "mem_bytes": {
                    "type": "integer"
                },
                "mem_slots": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "node_env": {
                    "type": "string"
                },
                "node_frozen": {
                    "type": "boolean"
                },
                "node_id": {
                    "type": "string"
                },
                "nodename": {
                    "type": "string"
                },
                "notifications": {
                    "type": "boolean"
                },
                "os_arch": {
                    "type": "string"
                },
                "os_concat": {
                    "type": "string"
                },
                "os_kernel": {
                    "type": "string"
                },
                "os_name": {
                    "type": "string"
                },
                "os_obs_alert_date": {
                    "type": "string"
                },
                "os_obs_warn_date": {
                    "type": "string"
                },
                "os_release": {
                    "type": "string"
                },
                "os_vendor": {
                    "type": "string"
                },
                "power_breaker1": {
                    "type": "string"
                },
                "power_breaker2": {
                    "type": "string"
                },
                "power_cabinet1": {
                    "type": "string"
                },
                "power_cabinet2": {
                    "type": "string"
                },
                "power_protect": {
                    "type": "string"
                },
                "power_protect_breaker": {
                    "type": "string"
                },
                "power_supply_nb": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "sec_zone": {
                    "type": "string"
                },
                "serial": {
                    "type": "string"
                },
                "snooze_till": {
                    "type": "string"
                },
                "sp_version": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "team_integ": {
                    "type": "string"
                },
                "team_responsible": {
                    "type": "string"
                },
                "team_support": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "tz": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "warranty_end": {
                    "type": "string"
                }
            }
        },
        "tables.NodeTag": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                },
                "tag_attach_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tag_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "tables.Service": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "svc_app": {
                    "type": "string"
                },
                "svc_avail_status": {
                    "type": "string"
                },
                "svc_config_updated": {
                    "type": "string"
                },
                "svc_env": {
                    "type": "string"
                },
                "svc_flex_max_nodes": {
                    "type": "integer"
                },
                "svc_flex_min_nodes": {
                    "type": "integer"
                },
                "svc_flex_target": {
                    "type": "integer"
                },
                "svc_frozen": {
                    "type": "string"
                },
                "svc_ha": {
                    "type": "string"
                },
                "svc_id": {
                    "type": "string"
                },
                "svc_placement": {
                    "type": "string"
                },
                "svc_provisioned": {
                    "type": "string"
                },
                "svc_snooze_till": {
                    "type": "string"
                },
                "svc_status": {
                    "type": "string"
                },
                "svc_topology": {
                    "type": "string"
                },
                "svc_wave": {
                    "type": "string"
                },
                "svcname": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "tables.ServiceTag": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "svc_id": {
                    "type": "string"
                },
                "tag_attach_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tag_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "tables.Tag": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "tag_created": {
                    "type": "string"
                },
                "tag_data": {
                    "type": "string"
                },
                "tag_exclude": {
                    "type": "string"
                },
                "tag_id": {
                    "type": "string"
                },
                "tag_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "tables.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "email_log_level": {
                    "type": "string"
                },
                "email_notifications": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "im_log_level": {
                    "type": "string"
                },
                "im_notifications": {
                    "type": "string"
                },
                "im_notifications_delay": {
                    "type": "integer"
                },
                "im_type": {
                    "type": "string"
                },
                "im_username": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "lock_filter": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_work": {
                    "type": "string"
                },
                "quota_app": {
                    "type": "integer"
                },
                "quota_docker_registries": {
                    "type": "integer"
                },
                "quota_org_group": {
                    "type": "integer"
                },
                "registration_id": {
                    "type": "string"
                },
                "registration_key": {
                    "type": "string"
                },
                "reset_password_key": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "OpenSVC collector API",
	Description: "Organization clusters, nodes, services and more.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
